spring:
  datasource:
    url: jdbc:mysql://database.c2krpnhphvoc.ap-northeast-2.rds.amazonaws.com:3306/db?characterEncoding=utf8
    username: admin
    password: ytsrq0116!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.musinsa.urlShort
  mapper-locations: mybatis/mapper/**/*.xml