spring:
  datasource:
    url: jdbc:log4jdbc:mysql://database.c2krpnhphvoc.ap-northeast-2.rds.amazonaws.com:3306/db?characterEncoding=utf8&serverTimezone=UTC
    username: admin
    password: ytsrq0116!
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  mvc:
    view:
      prefix: /templates
      suffix: .jsp
  error:
    whitelabel:
      enabled: falsed

logging:
  config: classpath:log4j2.xml
  level:
    root: info

mybatis:
  type-aliases-package: com.musinsa.urlShort
  mapper-locations: classpath:mybatis/mapper/**/*.xml